apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logto.fullname" . }}-ssl
  labels:
    {{- include "logto.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  {{- if .Values.database.sslcert }}
  cert.crt: |
    {{ .Values.database.sslcert | b64dec | nindent 4 }}
  {{- end }}
  {{- if .Values.database.sslkey }}
  cert.key: |
    {{ .Values.database.sslkey | b64dec | nindent 4 }}
  {{- end }}
  {{- if .Values.database.sslrootcert }}
  ca.pem: |
    {{ .Values.database.sslrootcert | b64dec | nindent 4 }}
  {{- end }}
